id = "angular-language-server"
name = "Angular Language Server"
version = "0.0.1"
schema_version = 1
authors = ["Pierre BOUILLON <pro.pierre.bouillon@proton.me>"]
description = "Angular language service support for Zed."
repository = "https://github.com/pBouillon/zed-angular-language-server"

[language_servers.angular-language-server]
name = "Angular Language Server"
languages = ["TypeScript", "HTML"]
